"""تولید پروژه‌ی واقعیِ React + Vite + Tailwind از همان سیستم طراحی.

تفاوت این خروجی با پیش‌نمایش HTML:

  HTML  (frilanser demo)  → پیش‌نمایش قفل‌شده برای کارفرما (واترمارک، غیرقابل استفاده)
  React (frilanser react) → کد واقعی و قابل اجرا برای شروع پروژه (`npm i && npm run dev`)

هر دو از یک منبع تغذیه می‌کنند: همان آرکتایپ، همان محتوا و **همان سیستم طراحی**
(سبک، پالت، فونت، شعاع و افکت‌ها). رنگ‌ها و فونت‌ها به `tailwind.config.js` و
`src/theme.js` تزریق می‌شوند تا کامپوننت‌ها فقط توکن‌ها را مصرف کنند.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from . import design_system as ds
from .demo_builder import _content, _brand_from_title, detect_archetype, choose_kind
from .models import Project
from .normalize import clean_text, slugify

# --------------------------------------------------------------------------- #
# الگوهای فایل‌ها
# --------------------------------------------------------------------------- #
PACKAGE_JSON = """{
  "name": "{{name}}",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.3.4",
    "autoprefixer": "^10.4.20",
    "postcss": "^8.4.49",
    "tailwindcss": "^3.4.17",
    "vite": "^5.4.11"
  }
}
"""

VITE_CONFIG = """import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: { host: true, port: 5173 },
})
"""

INDEX_HTML = """<!doctype html>
<html lang="fa" dir="rtl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{title}}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
"""

TAILWIND_CONFIG = """/** Generated by frilanser — پالت و فونت‌ها از سیستم طراحی گرفته شده‌اند */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '{{primary}}',
        accent: '{{accent}}',
        ink: '{{ink}}',
        muted: '{{mut}}',
        line: '{{line}}',
        bg: '{{bg}}',
        surface: '{{surface}}',
      },
      fontFamily: {
        heading: [{{heading_fonts}}],
        body: [{{body_fonts}}],
      },
      borderRadius: { card: '{{radius}}' },
      boxShadow: { card: '{{shadow}}' },
      backgroundImage: { hero: '{{gradient}}' },
    },
  },
  plugins: [],
}
"""

POSTCSS_CONFIG = """export default {
  plugins: { tailwindcss: {}, autoprefixer: {} },
}
"""

MAIN_JSX = """import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
"""

INDEX_CSS = """@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --p: {{primary}};
  --a: {{accent}};
  --grad: {{gradient}};
  --radius: {{radius}};
}

html, body, #root { height: 100%; }
body {
  margin: 0;
  background: theme('colors.bg');
  color: theme('colors.ink');
  font-family: theme('fontFamily.body');
  -webkit-font-smoothing: antialiased;
}
h1, h2, h3 { font-family: theme('fontFamily.heading'); }
{{extra_css}}
"""

THEME_JS = """/** توکن‌های طراحی — تولیدشده از سیستم طراحیِ فریلنس‌یار (سبک: {{style_label}}) */
export const theme = {
  style: '{{style_key}}',
  styleLabel: '{{style_label}}',
  palette: '{{palette_key}}',
  colors: {
    primary: '{{primary}}',
    accent: '{{accent}}',
    ink: '{{ink}}',
    muted: '{{mut}}',
    line: '{{line}}',
    bg: '{{bg}}',
    surface: '{{surface}}',
  },
  gradient: '{{gradient}}',
  radius: '{{radius}}',
  effects: {{effects}},
  fonts: { heading: '{{heading}}', body: '{{body}}' },
}

export default theme
"""

APP_JSX = """import React from 'react'
import content from './content.js'
import Nav from './components/Nav.jsx'
import Hero from './components/Hero.jsx'
import Services from './components/Services.jsx'
import Stats from './components/Stats.jsx'
import Products from './components/Products.jsx'
import Process from './components/Process.jsx'
import Pricing from './components/Pricing.jsx'
import Testimonials from './components/Testimonials.jsx'
import Faq from './components/Faq.jsx'
import Contact from './components/Contact.jsx'
import Cta from './components/Cta.jsx'
import Footer from './components/Footer.jsx'

export default function App() {
  return (
    <div className="min-h-screen bg-bg text-ink font-body">
      <Nav />
      <main>
        <Hero />
        <Services />
        <Stats />
        <Products />
        <Process />
        <Pricing />
        <Testimonials />
        <Faq />
        <Contact />
        <Cta />
      </main>
      <Footer />
    </div>
  )
}
"""

NAV_JSX = """import React, { useState } from 'react'
import content from '../content.js'

export default function Nav() {
  const [open, setOpen] = useState(false)
  return (
    <header className="sticky top-0 z-40 {{nav_surface}} border-b border-line">
      <div className="mx-auto max-w-6xl px-4 py-3 flex items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <span className="grid h-9 w-9 place-items-center rounded-xl bg-hero text-white font-heading text-lg">
            {content.brand.charAt(0)}
          </span>
          <span className="font-heading font-bold text-lg">{content.brand}</span>
        </div>
        <nav className="hidden md:flex items-center gap-6 text-sm text-muted">
          {content.nav.map((item) => (
            <a key={item} href="#" className="hover:text-primary transition-colors">{item}</a>
          ))}
        </nav>
        <button className="hidden md:inline-flex rounded-xl bg-primary px-5 py-2 text-white text-sm font-medium">
          {content.cta1}
        </button>
        <button
          onClick={() => setOpen((v) => !v)}
          className="md:hidden rounded-lg border border-line px-3 py-2 text-sm"
          aria-expanded={open}
          aria-label="منو"
        >
          ☰
        </button>
      </div>
      {open && (
        <nav className="md:hidden border-t border-line px-4 py-3 flex flex-col gap-3 text-sm">
          {content.nav.map((item) => (
            <a key={item} href="#" className="text-muted">{item}</a>
          ))}
        </nav>
      )}
    </header>
  )
}
"""

HERO_JSX = """import React from 'react'
import content from '../content.js'
import HeroArt from './HeroArt.jsx'

export default function Hero() {
  return (
    <section className="bg-hero text-white">
      <div className="mx-auto max-w-6xl px-4 py-16 grid gap-10 md:grid-cols-2 items-center">
        <div>
          <span className="inline-block rounded-full bg-white/20 px-4 py-1 text-xs backdrop-blur">
            {content.tagline}
          </span>
          <h1 className="mt-4 text-3xl md:text-4xl font-heading font-bold leading-snug">
            {content.hero_t}
          </h1>
          <p className="mt-4 text-white/90 leading-8 text-[15px]">{content.hero_d}</p>
          <div className="mt-7 flex flex-wrap gap-3">
            <button className="rounded-xl bg-white px-6 py-3 text-sm font-bold text-ink">
              {content.cta1}
            </button>
            <button className="rounded-xl border border-white/50 px-6 py-3 text-sm">
              {content.cta2}
            </button>
          </div>
          <div className="mt-6 flex flex-wrap gap-3 text-xs text-white/80">
            <span>✓ واکنش‌گرا</span><span>✓ سریع</span><span>✓ سئو پایه</span>
          </div>
        </div>
        <HeroArt />
      </div>
    </section>
  )
}
"""

HERO_ART_JSX = """import React from 'react'

/** تصویر جایگزینِ داخلی (SVG) — بدون نیاز به اینترنت */
export default function HeroArt() {
  return (
    <svg viewBox="0 0 520 360" className="w-full h-auto" role="img" aria-label="طرح صفحه اصلی">
      <defs>
        <linearGradient id="hg" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stopColor="#ffffff" stopOpacity="0.3" />
          <stop offset="1" stopColor="#ffffff" stopOpacity="0" />
        </linearGradient>
      </defs>
      <rect x="10" y="14" width="500" height="330" rx="22" fill="url(#hg)" />
      <rect x="48" y="52" width="424" height="150" rx="16" fill="#ffffff" opacity="0.92" />
      <rect x="70" y="76" width="120" height="12" rx="6" fill="#ffffff" opacity="0.55" />
      <rect x="70" y="100" width="220" height="10" rx="5" fill="#c7d0e6" />
      <rect x="70" y="122" width="170" height="10" rx="5" fill="#dbe1ee" />
      <rect x="330" y="86" width="112" height="82" rx="12" fill="#ffffff" opacity="0.35" />
      {[0, 1, 2].map((i) => (
        <rect key={i} x={48 + i * 143} y="222" width="130" height="104" rx="14"
              fill="#ffffff" opacity={0.9 - i * 0.15} />
      ))}
    </svg>
  )
}
"""

SERVICES_JSX = """import React from 'react'
import content from '../content.js'

export default function Services() {
  return (
    <section className="mx-auto max-w-6xl px-4 py-14">
      <h2 className="text-center text-2xl font-heading font-bold">امکاناتی که پیاده‌سازی می‌شود</h2>
      <p className="mt-2 text-center text-sm text-muted">
        هر بخش در نسخه‌ی نهایی به‌طور کامل و قابل استفاده تحویل می‌گردد
      </p>
      <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {content.services.map((s) => (
          <article key={s.title} className="{{card_class}} rounded-card p-5">
            <div className="mb-3 grid h-11 w-11 place-items-center rounded-xl bg-black/5 text-xl">
              {s.icon}
            </div>
            <h3 className="font-bold">{s.title}</h3>
            <p className="mt-1 text-sm text-muted leading-7">{s.desc}</p>
          </article>
        ))}
      </div>
    </section>
  )
}
"""

STATS_JSX = """import React from 'react'
import content from '../content.js'

export default function Stats() {
  return (
    <section className="bg-black/[.03] py-12">
      <div className="mx-auto max-w-6xl px-4 grid gap-6 text-center sm:grid-cols-2 lg:grid-cols-4">
        {content.stats.map((s) => (
          <div key={s.k}>
            <div className="text-3xl font-heading font-extrabold text-primary">{s.v}</div>
            <div className="mt-1 text-sm text-muted">{s.k}</div>
          </div>
        ))}
      </div>
    </section>
  )
}
"""

PRODUCTS_JSX = """import React from 'react'
import content from '../content.js'

export default function Products() {
  if (!content.products || content.products.length === 0) return null
  return (
    <section className="mx-auto max-w-6xl px-4 py-14">
      <h2 className="text-center text-2xl font-heading font-bold">نمونه محصولات</h2>
      <p className="mt-2 text-center text-sm text-muted">کارت محصول با تصویر، قیمت و دکمه‌ی خرید</p>
      <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {content.products.map((p) => (
          <article key={p.name} className="{{card_class}} overflow-hidden rounded-card">
            <div className="h-36 grid place-items-center text-4xl" style={{ background: p.color }}>
              🛍️
            </div>
            <div className="p-4">
              <h3 className="font-semibold text-[15px]">{p.name}</h3>
              <div className="mt-2 flex items-center gap-2">
                {p.old && <span className="text-xs text-muted line-through">{p.old}</span>}
                <span className="font-extrabold text-emerald-700">{p.price}</span>
                <span className="text-[11px] font-normal">تومان</span>
              </div>
            </div>
          </article>
        ))}
      </div>
    </section>
  )
}
"""

PROCESS_JSX = """import React from 'react'

const STEPS = ['نیازسنجی و جمع‌آوری نیازها', 'تایید طرح گرافیکی', 'اجرا و بارگذاری محتوا',
  'آموزش، تست و تحویل']

export default function Process() {
  return (
    <section className="bg-black/[.03] py-14">
      <div className="mx-auto max-w-6xl px-4">
        <h2 className="text-center text-2xl font-heading font-bold">مسیر همکاری</h2>
        <p className="mt-2 text-center text-sm text-muted">از امروز تا تحویل</p>
        <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {STEPS.map((t, i) => (
            <div key={t} className="{{card_class}} rounded-card p-5 text-center">
              <div className="mx-auto mb-2 grid h-9 w-9 place-items-center rounded-full bg-primary text-white text-sm">
                {i + 1}
              </div>
              <div className="font-semibold text-sm">{t}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
"""

PRICING_JSX = """import React from 'react'
import content from '../content.js'

const PLANS = [
  { name: 'پایه', tag: 'برای شروع', desc: 'صفحه‌ی اصلی + فرم تماس' },
  { name: 'حرفه‌ای', tag: 'پرفروش‌ترین', desc: 'چند صفحه + پنل مدیریت' },
  { name: 'سازمانی', tag: 'برای رشد', desc: 'صفحات بیشتر + سئو' },
]

export default function Pricing() {
  return (
    <section className="mx-auto max-w-6xl px-4 py-14">
      <h2 className="text-center text-2xl font-heading font-bold">بسته‌های پیشنهادی {content.brand}</h2>
      <p className="mt-2 text-center text-sm text-muted">
        قیمت نهایی همان مبلغی است که در پیشنهاد ارسالی می‌بینید
      </p>
      <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {PLANS.map((p) => (
          <div key={p.name} className="{{card_class}} rounded-card p-6 text-center">
            <div className="text-xs text-muted">{p.tag}</div>
            <h3 className="mt-1 text-lg font-bold">{p.name}</h3>
            <div className="mt-2 text-xl font-extrabold text-primary">توافقی</div>
            <p className="mt-2 text-sm text-muted">{p.desc}</p>
            <button className="mt-4 rounded-xl border border-primary px-5 py-2 text-sm text-primary">
              انتخاب بسته
            </button>
          </div>
        ))}
      </div>
    </section>
  )
}
"""

TESTIMONIALS_JSX = """import React from 'react'
import content from '../content.js'

const items = []
for (let i = 0; i < content.testimonials.length; i += 2) {
  items.push({ text: content.testimonials[i], who: content.testimonials[i + 1] || '' })
}

export default function Testimonials() {
  return (
    <section className="bg-black/[.03] py-14">
      <div className="mx-auto max-w-6xl px-4">
        <h2 className="text-center text-2xl font-heading font-bold">نظر کاربران</h2>
        <div className="mt-8 grid gap-4 sm:grid-cols-2">
          {items.map((t) => (
            <figure key={t.text} className="{{card_class}} rounded-card p-5">
              <blockquote className="text-sm text-muted leading-7">«{t.text}»</blockquote>
              <figcaption className="mt-4 flex items-center gap-3">
                <span className="h-9 w-9 rounded-full bg-hero" />
                <span className="text-sm font-semibold">{t.who}</span>
              </figcaption>
            </figure>
          ))}
        </div>
      </div>
    </section>
  )
}
"""

FAQ_JSX = """import React, { useState } from 'react'

const ROWS = [
  ['چه مدت طول می‌کشد؟', 'زمان تحویل دقیق در پیشنهاد ارسالی نوشته شده است.'],
  ['امکان تغییر بعد از تحویل دارم؟', 'بله؛ یک دور بازنگری رایگان پس از تحویل در نظر گرفته می‌شود.'],
  ['روی موبایل هم درست کار می‌کند؟', 'بله؛ طراحی کاملاً واکنش‌گرا است و روی موبایل تست می‌شود.'],
  ['پشتیبانی بعد از تحویل چطور است؟', 'رفع اشکال و آموزش کار با پنل پس از تحویل ارائه می‌شود.'],
]

export default function Faq() {
  const [open, setOpen] = useState(0)
  return (
    <section className="mx-auto max-w-3xl px-4 py-14">
      <h2 className="text-center text-2xl font-heading font-bold">سؤالات متداول</h2>
      <div className="mt-8 space-y-3">
        {ROWS.map(([q, a], i) => (
          <div key={q} className="{{card_class}} rounded-card">
            <button
              onClick={() => setOpen(open === i ? -1 : i)}
              className="flex w-full items-center justify-between gap-4 p-4 text-right"
              aria-expanded={open === i}
            >
              <span className="font-semibold text-[15px]">❓ {q}</span>
              <span className="text-primary text-xl">{open === i ? '−' : '+'}</span>
            </button>
            {open === i && <p className="px-4 pb-4 text-sm text-muted leading-7">{a}</p>}
          </div>
        ))}
      </div>
    </section>
  )
}
"""

CONTACT_JSX = """import React, { useState } from 'react'

export default function Contact() {
  const [sent, setSent] = useState(false)
  return (
    <section className="mx-auto max-w-6xl px-4 py-14">
      <h2 className="text-center text-2xl font-heading font-bold">تماس با ما</h2>
      <div className="mt-8 grid gap-6 md:grid-cols-[1.2fr_.8fr]">
        <form
          onSubmit={(e) => { e.preventDefault(); setSent(true) }}
          className="{{card_class}} rounded-card p-5"
        >
          <div className="grid gap-3 sm:grid-cols-2">
            <label className="text-sm">
              <span className="mb-1 block text-muted">نام و نام خانوادگی</span>
              <input className="w-full rounded-xl border border-line bg-white/70 px-3 py-2 text-sm"
                     placeholder="مثال: علی محمدی" />
            </label>
            <label className="text-sm">
              <span className="mb-1 block text-muted">شماره تماس</span>
              <input className="w-full rounded-xl border border-line bg-white/70 px-3 py-2 text-sm"
                     placeholder="09xxxxxxxxx" />
            </label>
          </div>
          <label className="mt-3 block text-sm">
            <span className="mb-1 block text-muted">توضیحات</span>
            <textarea rows="4" className="w-full rounded-xl border border-line bg-white/70 px-3 py-2 text-sm"
                      placeholder="متن پیام شما…" />
          </label>
          <button className="mt-4 rounded-xl bg-primary px-6 py-2.5 text-sm text-white">
            ارسال درخواست
          </button>
          {sent && <p className="mt-3 text-sm text-emerald-600">درخواست شما ثبت شد (نمونه).</p>}
        </form>
        <div className="space-y-3 text-sm">
          {[['📞 تلفن', '۰۲۱-۱۲۳۴۵۶۷۸'], ['✉️ ایمیل', 'info@example.com'],
            ['📍 آدرس', 'تهران، خیابان نمونه، پلاک ۱۲'], ['🕘 ساعات کاری', 'شنبه تا چهارشنبه ۹ تا ۱۸']]
            .map(([k, v]) => (
              <div key={k} className="{{card_class}} rounded-card p-4">
                <div className="font-semibold">{k}</div>
                <div className="text-muted">{v}</div>
              </div>
            ))}
        </div>
      </div>
    </section>
  )
}
"""

CTA_JSX = """import React from 'react'
import content from '../content.js'

export default function Cta() {
  return (
    <section className="py-12">
      <div className="mx-auto max-w-6xl px-4">
        <div className="rounded-3xl bg-hero px-6 py-12 text-center text-white">
          <h2 className="text-2xl font-heading font-bold">آماده‌ی شروع هستید؟</h2>
          <p className="mx-auto mt-2 max-w-xl text-sm text-white/90">
            {content.tagline} — همین امروز پیام بدهید تا زمان‌بندی قطعی شود.
          </p>
          <button className="mt-6 rounded-xl bg-white px-7 py-3 text-sm font-bold text-ink">
            {content.cta1}
          </button>
        </div>
      </div>
    </section>
  )
}
"""

FOOTER_JSX = """import React from 'react'
import content from '../content.js'

export default function Footer() {
  return (
    <footer className="bg-ink/95 py-10 text-sm text-white/70">
      <div className="mx-auto max-w-6xl px-4 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
        <div>
          <h4 className="mb-2 font-bold text-white">{content.brand}</h4>
          <p>{content.tagline}</p>
        </div>
        <div>
          <h4 className="mb-2 font-bold text-white">دسترسی سریع</h4>
          {content.nav.map((n) => <div key={n}>{n}</div>)}
        </div>
        <div>
          <h4 className="mb-2 font-bold text-white">خدمات</h4>
          {content.services.slice(0, 4).map((s) => <div key={s.title}>{s.title}</div>)}
        </div>
        <div>
          <h4 className="mb-2 font-bold text-white">تماس</h4>
          <div>info@example.com</div>
          <div>۰۲۱-۱۲۳۴۵۶۷۸</div>
        </div>
      </div>
      <div className="mt-8 border-t border-white/10 pt-4 text-center text-xs">
        تولیدشده با فریلنس‌یار آرنا — کد واقعی پروژه، آماده‌ی توسعه
      </div>
    </footer>
  )
}
"""

README_MD = """# {{brand}} — پروژه‌ی React آماده

این پوشه یک پروژه‌ی واقعی و قابل اجرا است که به‌طور خودکار از روی آگهی
«{{title}}» ساخته شده است.

- سبک طراحی: **{{style_label}}** (`{{style_key}}`)
- پالت رنگ: **{{palette_label}}** — تزریق‌شده به `tailwind.config.js` و `src/theme.js`
- فونت‌ها: {{heading}} / {{body}}

## اجرا

```bash
npm install
npm run dev          # http://localhost:5173
```

برای خروجی نهایی:

```bash
npm run build        # خروجی در dist/
npm run preview
```

## ساختار

```
src/
  theme.js           توکن‌های طراحی (رنگ، گرادینت، شعاع، افکت‌ها)
  content.js         همه‌ی متن‌های پروژه (فارسی)
  App.jsx            ترکیب صفحه
  components/        نوار، هیرو، خدمات، آمار، محصولات، گام‌ها،
                     قیمت، نظرات، سؤالات متداول، تماس، CTA، پاورقی
```

## نکته‌ها

- هیچ تصویر خارجی ندارد؛ تصویر هیرو یک SVG داخلی است (`components/HeroArt.jsx`).
- ریسپانسیو است (موبایل، تبلت، دسکتاپ) و جهتِ صفحه RTL است (`index.html`).
- دسترسی‌پذیری پایه رعایت شده: برچسب‌ها، نقش‌ها، حالت فوکس و منوی موبایل با `aria-expanded`.
- رنگ متن روی دکمه‌ها بر اساس کنتراست انتخاب شده است.
- برای تغییر رنگ/فونت/شعاع، فقط `src/theme.js` و `tailwind.config.js` را ویرایش کنید.
"""


# --------------------------------------------------------------------------- #
# تولید
# --------------------------------------------------------------------------- #
def _safe_pkg_name(project: Project) -> str:
    base = re.sub(r"[^a-z0-9\-]", "-", f"frilanser-{project.source}-{project.external_id}".lower())
    return re.sub(r"-+", "-", base).strip("-") or "frilanser-app"


def _font_list(stack: str) -> str:
    """تبدیل زنجیره‌ی فونت CSS به آرایه‌ی تنظیمات Tailwind."""
    parts = [p.strip().strip('"').strip("'") for p in stack.split(",") if p.strip()]
    return ", ".join(f"'{p}'" for p in parts)


def _fill(template: str, values: dict) -> str:
    out = template
    for key, val in values.items():
        out = out.replace("{{" + key + "}}", str(val))
    return out


def build_react_project(project: Project, screening: dict, proposal: dict | None,
                        out_dir: Path, style_override: str = "",
                        base_style: "ds.Style | None" = None) -> dict:
    """یک پروژه‌ی کامل Vite + React + Tailwind می‌سازد."""
    archetype = detect_archetype(project, screening)
    style = base_style or ds.pick_style(project, archetype, style_override or "")
    pal = ds.palette_of(style)
    fonts = ds.fonts_of(style)
    brand = _brand_from_title(project.title, archetype)
    c = _content(archetype, brand)
    c["brand"] = brand

    slug = slugify(f"{project.source}-{project.external_id}-react") or _safe_pkg_name(project)
    root = Path(out_dir) / slug
    if root.exists():
        for child in sorted(root.rglob("*"), reverse=True):
            if child.is_file():
                child.unlink()
    (root / "src" / "components").mkdir(parents=True, exist_ok=True)

    glass = "glass" in style.effects
    card_class = ("bg-white/60 backdrop-blur-md border border-white/40 shadow-card"
                  if glass else "bg-surface border border-line shadow-card")
    nav_surface = "bg-white/60 backdrop-blur-md" if glass else "bg-surface"
    extra_css = (
        "/* افکت شیشه‌ای */\n.glass { background: rgba(255,255,255,.6); backdrop-filter: blur(12px); }\n"
        if glass else ""
    )

    v = {
        "name": _safe_pkg_name(project),
        "title": clean_text(project.title),
        "brand": brand,
        "style_key": style.key, "style_label": style.label, "palette_key": pal.key,
        "palette_label": pal.label,
        "primary": pal.primary, "accent": pal.accent, "ink": pal.ink, "mut": pal.mut,
        "line": pal.line, "bg": pal.bg, "surface": pal.surface, "gradient": pal.gradient,
        "radius": style.radius, "shadow": style.shadow,
        "effects": json.dumps(list(style.effects), ensure_ascii=False),
        "heading": fonts.heading, "body": fonts.body,
        "heading_fonts": _font_list(fonts.heading), "body_fonts": _font_list(fonts.body),
        "card_class": card_class, "nav_surface": nav_surface, "extra_css": extra_css,
    }

    # محتوای فارسی پروژه
    content_js = {
        "brand": brand,
        "tagline": c["tagline"],
        "nav": list(c["nav"]),
        "hero_t": c["hero_t"], "hero_d": c["hero_d"],
        "cta1": c["cta1"], "cta2": c["cta2"],
        "about": c["about"],
        "services": [{"icon": s[0], "title": s[1], "desc": s[2]} for s in c["services"]],
        "stats": [{"v": s[0], "k": s[1]} for s in c["stats"]],
        "products": [{"name": p[0], "price": p[1], "old": p[2], "color": p[3]}
                     for p in (c.get("products") or [])],
        "testimonials": list(c["testimonials"]),
        "quote_items": list(c["quote_items"]),
        "deliverables": list(screening.get("deliverables") or []),
        "archetype": archetype,
        "style": style.key,
    }

    files: dict[str, str] = {
        "package.json": _fill(PACKAGE_JSON, v),
        "vite.config.js": VITE_CONFIG,
        "postcss.config.js": POSTCSS_CONFIG,
        "index.html": _fill(INDEX_HTML, v),
        "tailwind.config.js": _fill(TAILWIND_CONFIG, v),
        "src/main.jsx": MAIN_JSX,
        "src/index.css": _fill(INDEX_CSS, v),
        "src/theme.js": _fill(THEME_JS, v),
        "src/App.jsx": APP_JSX,
        "src/content.js": "/* محتوای پروژه — از روی آگهی تولید شده؛ هرچه خواستید اینجا ویرایش کنید */\n"
                          "const content = " + json.dumps(content_js, ensure_ascii=False, indent=2) +
                          "\n\nexport default content\n",
        "src/components/Nav.jsx": _fill(NAV_JSX, v),
        "src/components/Hero.jsx": _fill(HERO_JSX, v),
        "src/components/HeroArt.jsx": HERO_ART_JSX,
        "src/components/Services.jsx": _fill(SERVICES_JSX, v),
        "src/components/Stats.jsx": _fill(STATS_JSX, v),
        "src/components/Products.jsx": _fill(PRODUCTS_JSX, v),
        "src/components/Process.jsx": _fill(PROCESS_JSX, v),
        "src/components/Pricing.jsx": _fill(PRICING_JSX, v),
        "src/components/Testimonials.jsx": _fill(TESTIMONIALS_JSX, v),
        "src/components/Faq.jsx": _fill(FAQ_JSX, v),
        "src/components/Contact.jsx": _fill(CONTACT_JSX, v),
        "src/components/Cta.jsx": _fill(CTA_JSX, v),
        "src/components/Footer.jsx": _fill(FOOTER_JSX, v),
        "README.md": _fill(README_MD, {**v, "title": clean_text(project.title)}),
    }

    for rel, body in files.items():
        target = root / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body, encoding="utf-8")

    return {
        "project_id": project.id,
        "path": str(root),
        "slug": slug,
        "style": style.key,
        "style_label": style.label,
        "palette": pal.key,
        "files": len(files),
        "kind": choose_kind(screening, project),
        "stack": "react-vite-tailwind",
        "next_steps": ["cd " + str(root), "npm install", "npm run dev"],
        "built_at": __import__("datetime").datetime.now().isoformat(timespec="seconds"),
    }
