/** Generated by frilanser — پالت و فونت‌ها از سیستم طراحی گرفته شده‌اند */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#a16207',
        accent: '#d97706',
        ink: '#241a05',
        muted: '#7c6a45',
        line: '#f0e2c2',
        bg: '#fdf9ef',
        surface: '#ffffff',
      },
      fontFamily: {
        heading: ['B Nazanin', 'Vazirmatn', 'Georgia', 'serif'],
        body: ['B Nazanin', 'Vazirmatn', 'Tahoma', 'serif'],
      },
      borderRadius: { card: '6px' },
      boxShadow: { card: '0 16px 44px rgba(70,50,10,.28)' },
      backgroundImage: { hero: 'linear-gradient(135deg,#7c4a03 0%,#a16207 55%,#e0a53a 100%)' },
    },
  },
  plugins: [],
}
