/** Generated by frilanser — پالت و فونت‌ها از سیستم طراحی گرفته شده‌اند */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#0e9f6e',
        accent: '#22b8cf',
        ink: '#132a24',
        muted: '#5f6f6a',
        line: '#dceee7',
        bg: '#f4fbf8',
        surface: '#ffffff',
      },
      fontFamily: {
        heading: ['Vazirmatn', 'IRANSans', 'Segoe UI', 'Tahoma', 'sans-serif'],
        body: ['Vazirmatn', 'IRANSans', 'Segoe UI', 'Tahoma', 'sans-serif'],
      },
      borderRadius: { card: '16px' },
      boxShadow: { card: '0 10px 28px rgba(11,80,60,.10)' },
      backgroundImage: { hero: 'linear-gradient(135deg,#0b6b4f 0%,#0e9f6e 55%,#22b8cf 100%)' },
    },
  },
  plugins: [],
}
