/** Generated by frilanser — پالت و فونت‌ها از سیستم طراحی گرفته شده‌اند */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#1d4ed8',
        accent: '#0ea5e9',
        ink: '#111c3a',
        muted: '#5b6b8c',
        line: '#dde6f8',
        bg: '#f5f8fe',
        surface: '#ffffff',
      },
      fontFamily: {
        heading: ['Vazirmatn', 'IRANSans', 'Segoe UI', 'Tahoma', 'sans-serif'],
        body: ['Vazirmatn', 'IRANSans', 'Segoe UI', 'Tahoma', 'sans-serif'],
      },
      borderRadius: { card: '10px' },
      boxShadow: { card: '0 6px 18px rgba(16,32,70,.07)' },
      backgroundImage: { hero: 'linear-gradient(135deg,#12306b 0%,#1d4ed8 55%,#0ea5e9 100%)' },
    },
  },
  plugins: [],
}
